# Generated by Django 3.1.12 on 2022-04-21 20:30

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oder',
            old_name='date_orderd',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='oder',
            old_name='ref_code',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='oder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='oder',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='oder',
            name='user',
        ),
        migrations.AddField(
            model_name='oder',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='oder',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
